# Dockerfile для оркестратора
FROM golang:latest as builder


WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . ./
RUN CGO_ENABLED=0 GOOS=linux go build -o orchestrator ./cmd/orchestrator

# Финальный образ
FROM alpine:latest

WORKDIR /root/
COPY --from=builder /app/orchestrator .

EXPOSE 8080
CMD ["./orchestrator"]
